DROP TABLE IF EXISTS RESOURCES;
CREATE TABLE RESOURCES (
  ID        INT PRIMARY KEY,
  PARENT_ID INT,
  NAME      VARCHAR(255)
);

INSERT INTO RESOURCES (ID, PARENT_ID, NAME) VALUES
  (1, NULL, 'SLUB'),
  (2, 1, 'Opus/Document/10'),
  (3, 1, 'Opus/Document/20');

DROP TABLE IF EXISTS DOCUMENT_IDENTIFIERS;
CREATE TABLE DOCUMENT_IDENTIFIERS (
  ID          INT PRIMARY KEY,
  DOCUMENT_ID INT,
  TYPE        VARCHAR(20),
  VALUE       VARCHAR(255)
);

INSERT INTO DOCUMENT_IDENTIFIERS (ID, DOCUMENT_ID, TYPE, VALUE) VALUES
  (1, 3282, 'urn', 'urn:nbn:de:bsz:14-qucosa-32825');
