DROP TABLE IF EXISTS RESOURCES;

CREATE TABLE RESOURCES (
	ID INT PRIMARY KEY,
	PARENT_ID INT,
	NAME VARCHAR(255)
);

INSERT INTO RESOURCES (ID, PARENT_ID, NAME) VALUES
(1, null, 'SLUB'),
(2, 1, 'Opus/Document/10'),
(3, 1, 'Opus/Document/20');
